from enum import Enum


class DestinationAttributeTypeEnum(str, Enum):
    """
    Destination Attribute Type Enum
    """
    ITEM = 'ITEM'
    CLASS = 'CLASS'
    VENDOR = 'VENDOR'
    ACCOUNT = 'ACCOUNT'
    PROJECT = 'PROJECT'
    CUSTOMER = 'CUSTOMER'
    EMPLOYEE = 'EMPLOYEE'
    LOCATION = 'LOCATION'
    COST_TYPE = 'COST_TYPE'
    COST_CODE = 'COST_CODE'
    TAX_DETAIL = 'TAX_DETAIL'
    DEPARTMENT = 'DEPARTMENT'
    ALLOCATION = 'ALLOCATION'
    CCC_ACCOUNT = 'CCC_ACCOUNT'
    EXPENSE_TYPE = 'EXPENSE_TYPE'
    LOCATION_ENTITY = 'LOCATION_ENTITY'
    PAYMENT_ACCOUNT = 'PAYMENT_ACCOUNT'
    CHARGE_CARD_NUMBER = 'CHARGE_CARD_NUMBER'
    EXPENSE_PAYMENT_TYPE = 'EXPENSE_PAYMENT_TYPE'
    USER_DEFINED_DIMENSION = 'USER_DEFINED_DIMENSION'
