data = {
    'get_projects_destination_attributes':[
        {
            'RECORDNO':'113',
            'PROJECTID':'10066',
            'NAME':'Labhvam 2',
            'DESCRIPTION':'None',
            'CURRENCY':'AUD',
            'PROJECTCATEGORY':'Contract',
            'PROJECTSTATUS':'In Progress',
            'PARENTKEY':'None',
            'PARENTID':'None',
            'PARENTNAME':'None',
            'STATUS':'active',
            'CUSTOMERKEY':'42',
            'CUSTOMERID':'10066',
            'CUSTOMERNAME':'Med dot',
            'PROJECTTYPE':'AMP-Marketing',
            'DEPARTMENTNAME':'Services',
            'LOCATIONID':'600',
            'LOCATIONNAME':'Australia',
            'BUDGETID':'None',
            'MEGAENTITYID':'600',
            'MEGAENTITYNAME':'Australia'
        },
        {
            'RECORDNO':'112',
            'PROJECTID':'10065',
            'NAME':'Labhvam 3',
            'DESCRIPTION':'None',
            'CURRENCY':'AUD',
            'PROJECTCATEGORY':'Contract',
            'PROJECTSTATUS':'In Progress',
            'PARENTKEY':'None',
            'PARENTID':'None',
            'PARENTNAME':'None',
            'STATUS':'active',
            'CUSTOMERKEY':'43',
            'CUSTOMERID':'10065',
            'CUSTOMERNAME':'Med dot',
            'PROJECTTYPE':'AMP-Marketing',
            'DEPARTMENTNAME':'Services',
            'LOCATIONID':'600',
            'LOCATIONNAME':'Australia',
            'BUDGETID':'None',
            'MEGAENTITYID':'600',
            'MEGAENTITYNAME':'Australia'
        }
    ]
}