# Generated by Django 3.0.3 on 2021-02-08 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0005_auto_20210208_0548'),
        ('tasks', '0002_charge_card_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='ap_payment',
            field=models.ForeignKey(help_text='Reference to AP Payment', null=True, on_delete=django.db.models.deletion.PROTECT, to='sage_intacct.APPayment'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='sage_intacct_reimbursement',
            field=models.ForeignKey(help_text='Reference to Sage Intacct Reimbursement', null=True, on_delete=django.db.models.deletion.PROTECT, to='sage_intacct.SageIntacctReimbursement'),
        ),
    ]
