# Generated by Django 3.1.13 on 2021-12-29 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0014_journalentry_journalentrylineitem'),
        ('tasks', '0004_auto_20211203_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='journal_entry',
            field=models.ForeignKey(help_text='Reference to JournalEntry', null=True, on_delete=django.db.models.deletion.PROTECT, to='sage_intacct.journalentry'),
        ),
    ]
