# Generated by Django 3.2.14 on 2024-05-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_error_repetition_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='supdoc_id',
            field=models.CharField(help_text='Sage Intacct Attachments ID', max_length=255, null=True),
        ),
    ]
