# Generated by Django 4.2.20 on 2025-04-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_tasklog_triggered_by'),
        ('tasks', '0013_error_mapping_error_expense_group_ids'),
    ]

    operations = [
    ]
