# Generated by Django 4.2.22 on 2025-08-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_merge_20250410_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='re_attempt_export',
            field=models.BooleanField(default=False, help_text='Is re-attempt export'),
        ),
    ]
