# Generated by Django 4.2.26 on 2025-11-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_tasklog_re_attempt_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='is_attachment_upload_failed',
            field=models.BooleanField(default=False, help_text='Is attachment upload failed'),
        ),
    ]
