# Generated by Django 4.2.27 on 2026-01-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_tasklog_is_attachment_upload_failed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingPublication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
            ],
            options={
                'db_table': 'testing_publication',
            },
        ),
    ]
