language: "en-US"
tone_instructions: ""

reviews:
  profile: "chill"
  high_level_summary: false
  high_level_summary_in_walkthrough: false
  review_status: false
  collapse_walkthrough: true
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  auto_apply_labels: false
  in_progress_fortune: false

  path_filters:
    - "!**/migrations/**"
    - "!**/*.md"
    - "!**/tests/**"

  auto_review:
    enabled: false
    drafts: false
    ignore_title_keywords: []
    labels: []
    base_branches: []
    ignore_usernames: []
    
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false

chat:
  auto_reply: false

