# Generated by Django 3.0.3 on 2020-10-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0002_fund_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='exported_at',
            field=models.DateTimeField(help_text='Exported at', null=True),
        ),
    ]
