# Generated by Django 3.0.3 on 2021-01-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0004_auto_20201209_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='billable',
            field=models.BooleanField(help_text='Expense Billable or not', null=True),
        ),
    ]
