# Generated by Django 3.0.3 on 2021-02-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0005_auto_20210201_1527'),
        ('fyle', '0005_expense_billable'),
    ]

    operations = [
    ]
