# Generated by Django 3.0.3 on 2021-03-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0006_auto_20210208_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='org_id',
            field=models.CharField(help_text='Organization ID', max_length=255, null=True),
        ),
    ]
