# Generated by Django 3.1.14 on 2022-05-10 16:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0012_auto_20220210_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='exported',
        ),
        migrations.AddField(
            model_name='expense',
            name='file_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='File IDs', null=True, size=None),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_number',
            field=models.CharField(help_text='Expense payment number', max_length=55, null=True),
        ),
    ]
