# Generated by Django 3.1.14 on 2022-05-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0013_auto_20220510_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroupsettings',
            name='import_card_credits',
            field=models.BooleanField(default=False, help_text='Import Card Credits'),
        ),
    ]
