# Generated by Django 3.1.14 on 2022-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0014_expensegroupsettings_import_card_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='export_type',
            field=models.CharField(help_text='Expense Group exported as', max_length=50, null=True),
        ),
    ]
