# Generated by Django 3.1.14 on 2023-04-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0018_auto_20230427_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='report_title',
            field=models.TextField(blank=True, help_text='Report title', null=True),
        ),
    ]
