# Generated by Django 3.1.14 on 2023-06-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0025_auto_20230417_1124'),
        ('fyle', '0019_expense_report_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependentField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_import_enabled', models.BooleanField(help_text='Is Import Enabled')),
                ('project_field_id', models.IntegerField(help_text='Fyle Source Field ID')),
                ('cost_code_field_name', models.CharField(help_text='Fyle Cost Code Field Name', max_length=255)),
                ('cost_code_field_id', models.IntegerField(help_text='Fyle Cost Code Field ID')),
                ('cost_type_field_name', models.CharField(help_text='Fyle Cost Type Field Name', max_length=255)),
                ('cost_type_field_id', models.IntegerField(help_text='Fyle Cost Type Field ID')),
                ('last_successful_import_at', models.DateTimeField(help_text='Last Successful Import At', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'dependent_fields',
            },
        ),
    ]
