# Generated by Django 3.1.14 on 2023-06-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0025_auto_20230417_1124'),
        ('fyle', '0020_dependentfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DependentField',
            new_name='DependentFieldSetting',
        ),
        migrations.AlterModelTable(
            name='dependentfieldsetting',
            table='dependent_field_settings',
        ),
    ]
