# Generated by Django 3.1.14 on 2023-06-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0022_auto_20230619_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='posted_at',
            field=models.DateTimeField(help_text='Date when the money is taken from the bank', null=True),
        ),
    ]
