# Generated by Django 3.1.14 on 2023-07-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0023_expense_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='employee_name',
            field=models.CharField(help_text='Name of the Fyle employee', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='employee_name',
            field=models.CharField(help_text='Expense Group Employee Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='response_logs',
            field=models.JSONField(help_text='Reponse log of the export', null=True),
        ),
    ]
