# Generated by Django 3.1.14 on 2023-07-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0024_auto_20230705_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensefilter',
            name='custom_field_type',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('NUMBER', 'NUMBER'), ('TEXT', 'TEXT'), ('BOOLEAN', 'BOOLEAN')], help_text='Custom field type', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expensefilter',
            name='operator',
            field=models.CharField(choices=[('isnull', 'isnull'), ('in', 'in'), ('iexact', 'iexact'), ('icontains', 'icontains'), ('lt', 'lt'), ('lte', 'lte'), ('not_in', 'not_in'), ('yes', 'yes'), ('no', 'no')], help_text='Operator for the filter', max_length=255),
        ),
    ]
