# Generated by Django 3.1.14 on 2023-08-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0027_auto_20230801_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensegroupsettings',
            name='import_card_credits',
        ),
    ]
