# Generated by Django 3.2.14 on 2024-04-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0029_auto_20240130_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentfieldsetting',
            name='last_synced_at',
            field=models.DateTimeField(help_text='Last Synced At (Intacct)', null=True),
        ),
    ]
