# Generated by Django 3.2.14 on 2024-08-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0032_auto_20240703_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='export_url',
            field=models.CharField(help_text='Intacct URL for the exported expenses', max_length=255, null=True),
        ),
    ]
