# Generated by Django 4.2.18 on 2025-02-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0037_alter_dependentfieldsetting_cost_type_field_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentfieldsetting',
            name='is_cost_type_import_enabled',
            field=models.BooleanField(default=True, help_text='Is Cost Type Import Enabled'),
        ),
    ]
