# Generated by Django 4.2.28 on 2026-02-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0042_expense_expenses_workspa_ad984e_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expensegroup',
            index=models.Index(condition=models.Q(('exported_at__isnull', True)), fields=['workspace_id', 'fund_source'], name='eg_ws_fund_null_idx'),
        ),
    ]
