# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('internal', '0009_auto_generated_sql')]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER PUBLICATION events ADD TABLE public.cost_codes;
                ALTER TABLE public.cost_codes REPLICA IDENTITY FULL;
            """
        )
    ]
