# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('internal', '0006_auto_generated_sql')]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO django_q_schedule (func, args, schedule_type, minutes, next_run, repeats, cluster)
                    SELECT 'apps.internal.tasks.pause_and_resume_export_schedules', NULL, 'I', 1440, NOW() + interval '10 minute', -1, 'import'
                    WHERE NOT EXISTS (
                        SELECT 1
                        FROM django_q_schedule
                        WHERE func = 'apps.internal.tasks.pause_and_resume_export_schedules'
                        AND args IS NULL
                    );
            """,
            reverse_sql="""
                DELETE FROM django_q_schedule
                WHERE func = 'apps.internal.tasks.pause_and_resume_export_schedules'
                AND args IS NULL;
            """
        )
    ]
