# Generated by Django
from django.db import migrations
from apps.internal.helpers import safe_run_sql
sql_files = [
    'fyle-integrations-db-migrations/intacct/functions/trigger_auto_import.sql'
]
class Migration(migrations.Migration):
    dependencies = [('internal', '0009_auto_generate_sql')]
    operations = safe_run_sql(sql_files)
