# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('internal', '0014_auto_generated_sql')]

    operations = [
        migrations.RunSQL(
            sql="""
                update django_q_schedule set cluster = null where func in ('apps.internal.tasks.re_export_stuck_exports', 'apps.internal.tasks.pause_and_resume_export_schedules');
            """,
            reverse_sql="""
                update django_q_schedule set cluster = 'import' where func in ('apps.internal.tasks.re_export_stuck_exports', 'apps.internal.tasks.pause_and_resume_export_schedules');
            """
        )
    ]
