# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('internal', '0017_auto_generated_sql')]

    operations = [
        migrations.RunSQL(
            sql="""
                update django_q_schedule set cluster = null where func in ('apps.workspaces.tasks.run_email_notification', 'apps.mappings.tasks.construct_tasks_and_chain_import_fields_to_fyle');
            """,
            reverse_sql="""
                update django_q_schedule set cluster = 'import' where func in ('apps.workspaces.tasks.run_email_notification', 'apps.mappings.tasks.construct_tasks_and_chain_import_fields_to_fyle');
            """
        )
    ]
