# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0057_intacctsyncedtimestamp'),
        ('internal', '0023_auto_generated_sql'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO intacct_sync_timestamps (
                    workspace_id,
                    account_synced_at,              
                    vendor_synced_at,             
                    customer_synced_at,             
                    class_synced_at,                
                    employee_synced_at,             
                    item_synced_at,                 
                    location_synced_at,             
                    allocation_synced_at,           
                    tax_detail_synced_at,           
                    department_synced_at,           
                    project_synced_at,             
                    expense_type_synced_at,         
                    location_entity_synced_at,      
                    payment_account_synced_at,      
                    expense_payment_type_synced_at, 
                    created_at,                     
                    updated_at                     
                )
                SELECT 
                    w.id AS workspace_id,
                    NULL AS account_synced_at,
                    NULL AS vendor_synced_at,
                    NULL AS customer_synced_at,
                    NULL AS class_synced_at,
                    NULL AS employee_synced_at,
                    NULL AS item_synced_at,
                    NULL AS location_synced_at,
                    NULL AS allocation_synced_at,
                    NULL AS tax_detail_synced_at,
                    NULL AS department_synced_at,
                    NULL AS project_synced_at,
                    NULL AS expense_type_synced_at,
                    NULL AS location_entity_synced_at,
                    NULL AS payment_account_synced_at,
                    NULL AS expense_payment_type_synced_at,
                    NOW() AS created_at,
                    NOW() AS updated_at
                FROM workspaces w
                WHERE NOT EXISTS (
                    SELECT 1 
                    FROM intacct_sync_timestamps ist 
                    WHERE ist.workspace_id = w.id
                );
            """,
            reverse_sql="""
                DELETE FROM intacct_sync_timestamps;
            """
        )
    ]
