# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('sage_intacct', '0032_sageintacctattributescount'),('internal', '0025_auto_generated_sql')]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO sage_intacct_attributes_count (workspace_id, created_at, updated_at)
                SELECT id, now(), now()
                FROM workspaces
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM sage_intacct_attributes_count
                    WHERE workspace_id = workspaces.id
                );
            """,
            reverse_sql="""
                DELETE FROM sage_intacct_attributes_count
                WHERE EXISTS (
                    SELECT 1
                    FROM sage_intacct_attributes_count
                    WHERE workspace_id = sage_intacct_attributes_count.workspace_id
                );
            """
        )
    ]
