# Generated by Django 3.0.3 on 2021-01-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0002_ccc'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='default_item_id',
            field=models.CharField(help_text='Default item ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='default_item_name',
            field=models.CharField(help_text='Default item name', max_length=255, null=True),
        ),
    ]
