# Generated by Django 3.0.3 on 2021-02-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0003_auto_20210201_1604'),
        ('mappings', '0003_auto_20210127_1551'),
    ]

    operations = [
    ]
