# Generated by Django 3.0.3 on 2021-02-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0003_auto_20210127_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='payment_account_id',
            field=models.CharField(help_text='Sage Intacct Payment Account id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='payment_account_name',
            field=models.CharField(help_text='Sage Intacct Payment Account name', max_length=255, null=True),
        ),
    ]
