# Generated by Django 3.0.3 on 2021-05-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0004_auto_20210208_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='default_ccc_expense_payment_type_id',
            field=models.CharField(help_text='Default Expense Payment Type ID for ccc expenses', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='default_ccc_expense_payment_type_name',
            field=models.CharField(help_text='Default Expense Payment Type Name for ccc expenses', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='default_reimbursable_expense_payment_type_id',
            field=models.CharField(help_text='Default Expense Payment Type ID for reimbursable expenses', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='default_reimbursable_expense_payment_type_name',
            field=models.CharField(help_text='Default Expense Payment Type Name for reimbursable expenses', max_length=255, null=True),
        ),
    ]
