# Generated by Django 3.0.3 on 2021-07-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0006_auto_20210603_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='location_entity_id',
            field=models.CharField(help_text='Location Entity ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='location_entity_name',
            field=models.CharField(help_text='Location Entity name', max_length=255, null=True),
        ),
    ]
