# Generated by Django 3.0.3 on 2021-08-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0007_auto_20210705_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='default_class_id',
            field=models.CharField(help_text='Default class ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='default_class_name',
            field=models.CharField(help_text='Default class name', max_length=255, null=True),
        ),
    ]
