# Generated by Django 3.0.3 on 2021-10-28 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_auto_20210723_1010'),
        ('mappings', '0008_auto_20210831_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmapping',
            name='workspace',
            field=models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace'),
        ),
    ]
