# Generated by Django 3.1.14 on 2022-02-21 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_auto_20211229_1347'),
        ('mappings', '0008_auto_20210831_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationEntityMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_entity_name', models.CharField(help_text='NetSuite Subsidiary name', max_length=255)),
                ('country_name', models.CharField(help_text='Netsuite Subsidiary Country', max_length=255, null=True)),
                ('destination_id', models.CharField(help_text='NetSuite Subsidiary id', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'location_entity_mappings',
            },
        ),
    ]
