# Generated by Django 3.1.14 on 2022-10-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0010_locationentitymapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='default_credit_card_id',
            field=models.CharField(help_text='Default credit card ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='default_credit_card_name',
            field=models.CharField(help_text='Default credit card name', max_length=255, null=True),
        ),
    ]
