# Generated by Django 3.1.14 on 2023-04-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0011_auto_20221010_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmapping',
            name='default_gl_account_id',
            field=models.CharField(help_text='Default credit card ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalmapping',
            name='default_gl_account_name',
            field=models.CharField(help_text='Default credit card name', max_length=255, null=True),
        ),
    ]
