# Generated by Django 3.1.14 on 2023-06-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0025_auto_20230417_1124'),
        ('mappings', '0012_auto_20230417_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_type', models.CharField(help_text='Attribute type', max_length=150)),
                ('status', models.CharField(choices=[('ENQUEUED', 'ENQUEUED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED'), ('FATAL', 'FATAL')], help_text='Status', max_length=255, null=True)),
                ('error_log', models.JSONField(default=list, help_text='Error Log')),
                ('queued_batches_count', models.IntegerField(default=0, help_text='Queued batches')),
                ('processed_batches_count', models.IntegerField(default=0, help_text='Processed batches')),
                ('last_successful_run_at', models.DateTimeField(help_text='Last successful run', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('workspace', models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'import_logs',
                'unique_together': {('workspace', 'attribute_type')},
            },
        ),
    ]
