# Generated by Django 3.1.14 on 2023-07-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0030_lastexportdetail'),
        ('mappings', '0014_auto_20230531_1248'),
    ]

    operations = []
