# Generated by Django 3.0.3 on 2020-10-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0002_charge_card_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='memo',
            field=models.CharField(help_text='Sage Intacct docnumber', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chargecardtransaction',
            name='memo',
            field=models.CharField(help_text='Sage Intacct referenceno', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='memo',
            field=models.CharField(help_text='Sage Intacct memo', max_length=255, null=True),
        ),
    ]
