# Generated by Django 3.0.3 on 2020-12-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0002_charge_card_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billlineitem',
            name='spent_at',
        ),
        migrations.RemoveField(
            model_name='expensereportlineitem',
            name='spent_at',
        ),
        migrations.AddField(
            model_name='bill',
            name='transaction_date',
            field=models.DateTimeField(help_text='Bill transaction date', null=True),
        ),
        migrations.AddField(
            model_name='chargecardtransaction',
            name='transaction_date',
            field=models.DateTimeField(help_text='Safe Intacct Charge Card transaction date', null=True),
        ),
        migrations.AddField(
            model_name='chargecardtransactionlineitem',
            name='memo',
            field=models.CharField(help_text='Sage Intacct lineitem description', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='transaction_date',
            field=models.DateTimeField(help_text='Expense Report transaction date', null=True),
        ),
        migrations.AddField(
            model_name='expensereportlineitem',
            name='transaction_date',
            field=models.DateTimeField(help_text='Expense Report transaction date', null=True),
        ),
    ]
