# Generated by Django 3.0.3 on 2021-02-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0005_auto_20210201_1527'),
        ('sage_intacct', '0003_auto_20201209_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_account_id', models.CharField(help_text='Sage Intacct Payment Account ID', max_length=255)),
                ('vendor_id', models.CharField(help_text='Sage Intacct Vendor ID', max_length=255)),
                ('description', models.TextField(help_text='Payment Description')),
                ('currency', models.CharField(help_text='AP Payment Currency', max_length=255)),
                ('created_at', models.DateField(auto_now=True, help_text='Created at')),
                ('updated_at', models.DateField(auto_now=True, help_text='Updated at')),
                ('expense_group', models.OneToOneField(help_text='Expense group reference', on_delete=django.db.models.deletion.PROTECT, to='fyle.ExpenseGroup')),
            ],
            options={
                'db_table': 'ap_payments',
            },
        ),
        migrations.CreateModel(
            name='SageIntacctReimbursement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(help_text='Sage Intacct Account ID', max_length=255)),
                ('employee_id', models.CharField(help_text='Sage Intacct Employee ID', max_length=255)),
                ('memo', models.TextField(help_text='Reimbursement Memo')),
                ('payment_description', models.TextField(help_text='Reimbursement Description')),
                ('created_at', models.DateField(auto_now=True, help_text='Created at')),
                ('updated_at', models.DateField(auto_now=True, help_text='Updated at')),
                ('expense_group', models.OneToOneField(help_text='Expense group reference', on_delete=django.db.models.deletion.PROTECT, to='fyle.ExpenseGroup')),
            ],
            options={
                'db_table': 'sage_intacct_reimbursements',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_on_sage_intacct',
            field=models.BooleanField(default=False, help_text='Payment status in Sage Intacct'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_synced',
            field=models.BooleanField(default=False, help_text='Payment synced status'),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='paid_on_sage_intacct',
            field=models.BooleanField(default=False, help_text='Payment status in Sage Intacct'),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='payment_synced',
            field=models.BooleanField(default=False, help_text='Payment synced status'),
        ),
        migrations.CreateModel(
            name='SageIntacctReimbursementLineitem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(help_text='Reimbursement amount')),
                ('record_key', models.CharField(help_text='Sage Intacct Record Key', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('sage_intacct_reimbursement', models.ForeignKey(help_text='Reference to Sage Intacct Reimbursement', on_delete=django.db.models.deletion.PROTECT, to='sage_intacct.SageIntacctReimbursement')),
            ],
            options={
                'db_table': 'sage_intacct_reimbursement_lineitems',
            },
        ),
        migrations.CreateModel(
            name='APPaymentLineitem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(help_text='AP Payment amount')),
                ('record_key', models.CharField(help_text='Sage Intacct Record Key', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('ap_payment', models.ForeignKey(help_text='Reference to AP Payment', on_delete=django.db.models.deletion.PROTECT, to='sage_intacct.APPayment')),
            ],
            options={
                'db_table': 'ap_payment_lineitems',
            },
        ),
    ]
