# Generated by Django 3.0.3 on 2021-02-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0003_auto_20201209_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_on_sage',
            field=models.BooleanField(default=False, help_text='Payment status in sage'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_synced',
            field=models.BooleanField(default=False, help_text='Payment synced status'),
        ),
    ]
