# Generated by Django 3.0.3 on 2021-01-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0003_auto_20201209_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='billlineitem',
            name='billable',
            field=models.BooleanField(help_text='Expense Billable or not', null=True),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='customer_id',
            field=models.CharField(help_text='Sage Intacct customer id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='item_id',
            field=models.CharField(help_text='Sage Intacct iten id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chargecardtransactionlineitem',
            name='customer_id',
            field=models.CharField(help_text='Sage Intacct customer id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chargecardtransactionlineitem',
            name='item_id',
            field=models.CharField(help_text='Sage Intacct iten id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensereportlineitem',
            name='billable',
            field=models.BooleanField(help_text='Expense Billable or not', null=True),
        ),
        migrations.AddField(
            model_name='expensereportlineitem',
            name='customer_id',
            field=models.CharField(help_text='Sage Intacct customer id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensereportlineitem',
            name='item_id',
            field=models.CharField(help_text='Sage Intacct iten id', max_length=255, null=True),
        ),
    ]
