# Generated by Django 3.0.3 on 2021-02-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0004_auto_20210127_1345'),
        ('sage_intacct', '0004_auto_20210204_1750'),
    ]

    operations = [
    ]
