# Generated by Django 3.0.3 on 2021-02-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0005_auto_20210208_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='currency',
            field=models.CharField(default='USD', help_text='Expense Report Currency', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargecardtransaction',
            name='currency',
            field=models.CharField(default='USD', help_text='Expense Report Currency', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensereport',
            name='currency',
            field=models.CharField(default='USD', help_text='Expense Report Currency', max_length=5),
            preserve_default=False,
        ),
    ]
