# Generated by Django 3.0.3 on 2021-03-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0006_auto_20210224_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='memo',
            field=models.TextField(help_text='Sage Intacct docnumber', null=True),
        ),
        migrations.AlterField(
            model_name='billlineitem',
            name='memo',
            field=models.TextField(help_text='Sage Intacct lineitem description', null=True),
        ),
        migrations.AlterField(
            model_name='chargecardtransaction',
            name='memo',
            field=models.TextField(help_text='Sage Intacct referenceno', null=True),
        ),
        migrations.AlterField(
            model_name='chargecardtransactionlineitem',
            name='memo',
            field=models.TextField(help_text='Sage Intacct lineitem description', null=True),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='memo',
            field=models.TextField(help_text='Sage Intacct memo', null=True),
        ),
        migrations.AlterField(
            model_name='expensereportlineitem',
            name='memo',
            field=models.TextField(help_text='Sage Intacct lineitem description', null=True),
        ),
    ]
