# Generated by Django 3.0.3 on 2021-05-21 10:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0008_auto_20210408_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='billlineitem',
            name='user_defined_dimensions',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Sage Intacct User Defined Dimensions', null=True),
        ),
        migrations.AddField(
            model_name='expensereportlineitem',
            name='user_defined_dimensions',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Sage Intacct User Defined Dimensions', null=True),
        ),
    ]
