# Generated by Django 3.0.3 on 2021-05-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0009_auto_20210521_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereportlineitem',
            name='expense_payment_type',
            field=models.CharField(help_text='Expense Payment Type', max_length=255, null=True),
        ),
    ]
