# Generated by Django 3.0.3 on 2021-07-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0010_expensereportlineitem_expense_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='location_entity_id',
            field=models.CharField(help_text='Sage Intacct Location Entity ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='location_entity_id',
            field=models.CharField(help_text='Sage Intacct Location Entity ID', max_length=255, null=True),
        ),
    ]
