# Generated by Django 3.0.3 on 2021-09-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0011_billlineitem_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargecardtransactionlineitem',
            name='class_id',
            field=models.CharField(help_text='Sage Intacct class id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensereportlineitem',
            name='class_id',
            field=models.CharField(help_text='Sage Intacct class id', max_length=255, null=True),
        ),
    ]
