# Generated by Django 3.1.13 on 2021-12-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0012_auto_20210907_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billlineitem',
            name='user_defined_dimensions',
            field=models.JSONField(help_text='Sage Intacct User Defined Dimensions', null=True),
        ),
        migrations.AlterField(
            model_name='expensereportlineitem',
            name='user_defined_dimensions',
            field=models.JSONField(help_text='Sage Intacct User Defined Dimensions', null=True),
        ),
    ]
