# Generated by Django 3.1.13 on 2021-12-24 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0014_journalentry_journalentrylineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentrylineitem',
            name='journal_entry',
            field=models.ForeignKey(help_text='Reference to Journal Entry', on_delete=django.db.models.deletion.PROTECT, to='sage_intacct.journalentry'),
        ),
    ]
