# Generated by Django 3.1.14 on 2022-12-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0017_auto_20220210_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appayment',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Created at'),
        ),
        migrations.AlterField(
            model_name='sageintacctreimbursement',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Created at'),
        ),
    ]
