# Generated by Django 3.1.14 on 2022-12-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0018_auto_20221209_0901'),
        ('sage_intacct', '0018_auto_20221213_0819'),
    ]

    operations = [
    ]
