# Generated by Django 3.1.14 on 2023-03-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0018_auto_20221213_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereportlineitem',
            name='task_id',
            field=models.CharField(help_text='Sage Intacct Task Id', max_length=255, null=True),
        ),
    ]
