# Generated by Django 3.1.14 on 2023-03-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0018_auto_20221213_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='billlineitem',
            name='cost_type_id',
            field=models.CharField(help_text='Sage intacct Task Id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='task_id',
            field=models.CharField(help_text='Sage intacct Task Id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chargecardtransactionlineitem',
            name='cost_type_id',
            field=models.CharField(help_text='Sage Intacct Cost Type Id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chargecardtransactionlineitem',
            name='task_id',
            field=models.CharField(help_text='Sage Intacct Task Id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensereportlineitem',
            name='cost_type_id',
            field=models.CharField(help_text='Sage Intacct Cost Type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensereportlineitem',
            name='task_id',
            field=models.CharField(help_text='Sage Intacct Task Id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalentrylineitem',
            name='cost_type_id',
            field=models.CharField(help_text='Sage Intacct Cost Type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalentrylineitem',
            name='task_id',
            field=models.CharField(help_text='Sage Intacct Task', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journalentrylineitem',
            name='item_id',
            field=models.CharField(help_text='Sage Intacct item id', max_length=255, null=True),
        ),
    ]
