# Generated by Django 3.1.14 on 2023-03-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0020_billlineitem_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billlineitem',
            name='cost_type_id',
            field=models.CharField(help_text='Sage intacct Task Id', max_length=255, null=True),
        ),
    ]
