# Generated by Django 3.1.14 on 2023-06-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0022_auto_20230615_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtype',
            name='record_number',
            field=models.CharField(help_text='Sage Intacct Record No', max_length=255),
        ),
    ]
