# Generated by Django 3.2.14 on 2024-04-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0024_chargecardtransactionlineitem_user_defined_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='costtype',
            name='is_imported',
            field=models.BooleanField(default=False, help_text='Is Imported'),
        ),
    ]
