# Generated by Django 3.2.14 on 2024-07-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0025_costtype_is_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='billlineitem',
            name='allocation_id',
            field=models.CharField(help_text='Sage Intacct Allocation id', max_length=255, null=True),
        ),
    ]
