# Generated by Django 3.2.14 on 2024-09-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0027_journalentrylineitem_allocation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargecardtransactionlineitem',
            name='billable',
            field=models.BooleanField(help_text='Expense Billable or not', null=True),
        ),
    ]
