# Generated by Django 4.2.20 on 2025-05-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0043_configuration_skip_accounting_export_summary_post'),
        ('sage_intacct', '0030_auto_20241112_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='Task Id', max_length=255, null=True)),
                ('task_name', models.CharField(help_text='Task Name', max_length=255, null=True)),
                ('project_id', models.CharField(help_text='Project Id', max_length=255, null=True)),
                ('project_name', models.CharField(help_text='Project Name', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(help_text='Reference to Workspace', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'cost_codes',
                'indexes': [models.Index(fields=['workspace', 'task_id'], name='cost_codes_workspa_1590e9_idx'), models.Index(fields=['workspace', 'project_id'], name='cost_codes_workspa_5ac5ff_idx')],
                'unique_together': {('workspace', 'task_id', 'project_id')},
            },
        ),
    ]
