# Generated by Django 4.2.26 on 2025-11-21 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0057_intacctsyncedtimestamp'),
        ('sage_intacct', '0031_costcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SageIntacctAttributesCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accounts_count', models.IntegerField(default=0, help_text='Number of accounts in Sage Intacct')),
                ('items_count', models.IntegerField(default=0, help_text='Number of items in Sage Intacct')),
                ('vendors_count', models.IntegerField(default=0, help_text='Number of vendors in Sage Intacct')),
                ('employees_count', models.IntegerField(default=0, help_text='Number of employees in Sage Intacct')),
                ('departments_count', models.IntegerField(default=0, help_text='Number of departments in Sage Intacct')),
                ('classes_count', models.IntegerField(default=0, help_text='Number of classes in Sage Intacct')),
                ('customers_count', models.IntegerField(default=0, help_text='Number of customers in Sage Intacct')),
                ('projects_count', models.IntegerField(default=0, help_text='Number of projects in Sage Intacct')),
                ('locations_count', models.IntegerField(default=0, help_text='Number of locations in Sage Intacct')),
                ('expense_types_count', models.IntegerField(default=0, help_text='Number of expense types in Sage Intacct')),
                ('tax_details_count', models.IntegerField(default=0, help_text='Number of tax details in Sage Intacct')),
                ('cost_codes_count', models.IntegerField(default=0, help_text='Number of cost codes (tasks) in Sage Intacct')),
                ('cost_types_count', models.IntegerField(default=0, help_text='Number of cost types in Sage Intacct')),
                ('user_defined_dimensions_details', models.JSONField(blank=True, default=dict, help_text='Count breakdown per UDD dimension (e.g., {"DEPARTMENT": 150, "PROJECT": 500}). Not exposed via API.', null=True)),
                ('charge_card_accounts_count', models.IntegerField(default=0, help_text='Number of charge card accounts in Sage Intacct')),
                ('payment_accounts_count', models.IntegerField(default=0, help_text='Number of payment accounts in Sage Intacct')),
                ('expense_payment_types_count', models.IntegerField(default=0, help_text='Number of expense payment types in Sage Intacct')),
                ('allocations_count', models.IntegerField(default=0, help_text='Number of allocations in Sage Intacct')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Updated at datetime')),
                ('workspace', models.OneToOneField(help_text='Reference to workspace', on_delete=django.db.models.deletion.PROTECT, related_name='sage_intacct_attributes_count', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'sage_intacct_attributes_count',
            },
        ),
    ]
