# Generated by Django 4.2.27 on 2025-12-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0032_sageintacctattributescount'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargecardtransactionlineitem',
            name='vendor_id',
            field=models.CharField(help_text='Sage Intacct Vendor Id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensereportlineitem',
            name='vendor_id',
            field=models.CharField(help_text='Sage Intacct Vendor Id', max_length=255, null=True),
        ),
    ]
