# Generated by Django 4.2.27 on 2025-12-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_intacct', '0033_chargecardtransactionlineitem_vendor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargecardtransactionlineitem',
            name='employee_id',
            field=models.CharField(help_text='Sage Intacct employee id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensereportlineitem',
            name='employee_id',
            field=models.CharField(help_text='Sage Intacct employee id', max_length=255, null=True),
        ),
    ]
