# Generated by Django 3.0.3 on 2021-02-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_auto_20201228_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='sync_fyle_to_sage_payments',
            field=models.BooleanField(default=False, help_text='Auto Sync Payments from Fyle to SAGE'),
        ),
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='sync_sage_to_fyle_payments',
            field=models.BooleanField(default=False, help_text='Auto Sync Payments from SAGE to Fyle'),
        ),
    ]
