# Generated by Django 3.0.3 on 2021-02-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_auto_20201228_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='sync_fyle_to_sage_intacct_payments',
            field=models.BooleanField(default=False, help_text='Auto Sync Payments from Fyle to Sage Intacct'),
        ),
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='sync_sage_intacct_to_fyle_payments',
            field=models.BooleanField(default=False, help_text='Auto Sync Payments from Sage Intacct to Fyle'),
        ),
    ]
