# Generated by Django 3.0.3 on 2021-02-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_workspacegeneralsettings_import_projects'),
        ('workspaces', '0005_auto_20210204_1750'),
    ]

    operations = [
    ]
