# Generated by Django 3.0.3 on 2021-02-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_auto_20210208_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegeneralsettings',
            name='auto_map_employees',
            field=models.CharField(help_text='Auto Map Employees type from NetSuite to Fyle', max_length=50, null=True),
        ),
    ]
