# Generated by Django 3.0.3 on 2021-06-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_auto_20210422_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='cluster_domain',
            field=models.CharField(help_text='Cluster Domain', max_length=255, null=True),
        ),
    ]
