# Generated by Django 3.0.3 on 2021-07-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_workspace_cluster_domain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkspaceGeneralSettings',
            new_name='Configuration',
        ),
        migrations.AlterModelTable(
            name='configuration',
            table='configurations',
        ),
    ]