# Generated by Django 3.0.3 on 2021-07-22 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_workspace_cluster_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(help_text='Unique Id to identify a workspace', primary_key=True, serialize=False)),
                ('reimbursable_expenses_object', models.CharField(choices=[('EXPENSE REPORT', 'EXPENSE REPORT'), ('BILL', 'BILL')], help_text='Mapping Settings ( BILL / EXPENSE_REPORT )', max_length=50)),
                ('corporate_credit_card_expenses_object', models.CharField(choices=[('EXPENSE REPORT', 'EXPENSE REPORT'), ('BILL', 'BILL'), ('CHARGE CARD TRANSACTION', 'CHARGE CARD TRANSACTION')], help_text='Mapping Settings ( BILL / CHARGE_CARD_TRANSACTION )', max_length=50, null=True)),
                ('import_projects', models.BooleanField(default=False, help_text='Auto import projects to Fyle')),
                ('import_categories', models.BooleanField(default=False, help_text='Auto import caimport_categories to Fyle')),
                ('sync_fyle_to_sage_intacct_payments', models.BooleanField(default=False, help_text='Auto Sync Payments from Fyle to Sage Intacct')),
                ('sync_sage_intacct_to_fyle_payments', models.BooleanField(default=False, help_text='Auto Sync Payments from Sage Intacct to Fyle')),
                ('auto_map_employees', models.CharField(choices=[('EMAIL', 'EMAIL'), ('NAME', 'NAME'), ('EMPLOYEE_CODE', 'EMPLOYEE_CODE')], help_text='Auto Map Employees type from Sage Intacct to Fyle', max_length=50, null=True)),
                ('auto_create_destination_entity', models.BooleanField(default=False, help_text='Auto create vendor / employee')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('workspace', models.OneToOneField(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.Workspace')),
            ],
            options={
                'db_table': 'configurations',
            },
        ),
        migrations.DeleteModel(
            name='WorkspaceGeneralSettings',
        ),
    ]
