# Generated by Django 3.0.3 on 2021-07-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_auto_20210723_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='auto_map_employees',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('NAME', 'NAME'), ('EMPLOYEE_CODE', 'EMPLOYEE_CODE')], help_text='Auto Map Employees type from Sage Intacct to Fyle', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='corporate_credit_card_expenses_object',
            field=models.CharField(choices=[('EXPENSE_REPORT', 'EXPENSE_REPORT'), ('BILL', 'BILL'), ('CHARGE_CARD_TRANSACTION', 'CHARGE_CARD_TRANSACTION')], help_text='Mapping Settings ( BILL / CHARGE_CARD_TRANSACTION )', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='reimbursable_expenses_object',
            field=models.CharField(choices=[('EXPENSE_REPORT', 'EXPENSE_REPORT'), ('BILL', 'BILL')], help_text='Mapping Settings ( BILL / EXPENSE_REPORT )', max_length=50),
        ),
    ]
