# Generated by Django 3.1.13 on 2021-12-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_configuration_memo_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='corporate_credit_card_expenses_object',
            field=models.CharField(choices=[('EXPENSE_REPORT', 'EXPENSE_REPORT'), ('BILL', 'BILL'), ('CHARGE_CARD_TRANSACTION', 'CHARGE_CARD_TRANSACTION'), ('JOURNAL_ENTRY', 'JOURNAL_ENTRY')], help_text='Mapping Settings ( BILL / CHARGE_CARD_TRANSACTION )', max_length=50, null=True),
        ),
    ]
