# Generated by Django 3.1.14 on 2022-02-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_auto_20211229_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='import_tax_codes',
            field=models.BooleanField(default=False, help_text='Auto import tax codes to Fyle', null=True),
        ),
        migrations.AddField(
            model_name='fylecredential',
            name='cluster_domain',
            field=models.CharField(default='https://staging.fyle.tech', help_text='cluster doman', max_length=255),
        ),
    ]
