# Generated by Django 3.1.14 on 2022-02-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_auto_20211229_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='fylecredential',
            name='cluster_domain',
            field=models.TextField(help_text='Cluster Domain', null=True),
        ),
    ]
