# Generated by Django 3.1.14 on 2022-03-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0016_fylecredential_cluster_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='import_tax_codes',
            field=models.BooleanField(default=False, help_text='Auto import tax codes to Fyle', null=True),
        ),
    ]
