# Generated by Django 3.1.14 on 2022-05-10 16:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0018_auto_20220427_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceschedule',
            name='emails_selected',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='Emails that has to be send mail', null=True, size=None),
        ),
    ]
