# Generated by Django 3.1.14 on 2022-05-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0019_auto_20220510_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='change_accounting_period',
            field=models.BooleanField(default=False, help_text='Change the accounting period'),
        ),
    ]
