# Generated by Django 3.1.14 on 2023-03-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0023_auto_20221213_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='is_simplify_report_closure_enabled',
            field=models.BooleanField(default=True, help_text='Simplify report closure is enbaled'),
        ),
    ]
