# Generated by Django 3.1.14 on 2023-06-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0028_auto_20230620_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='app_version',
            field=models.CharField(choices=[('v1', 'v1'), ('v2', 'v2')], default='v2', help_text='App version', max_length=2),
        ),
        migrations.AlterField(
            model_name='sageintacctcredential',
            name='si_company_name',
            field=models.TextField(help_text='Stores Sage Intacct company name', null=True),
        ),
    ]
