# Generated by Django 3.1.14 on 2023-08-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0030_lastexportdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastexportdetail',
            name='next_export',
            field=models.DateTimeField(help_text='next export datetime', null=True),
        ),
    ]
