# Generated by Django 3.1.14 on 2023-08-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0031_lastexportdetail_next_export'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastexportdetail',
            old_name='next_export',
            new_name='next_export_at',
        ),
    ]
