# Generated by Django 3.2.14 on 2024-07-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0034_configuration_is_journal_credit_billable'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='auto_create_merchants_as_vendors',
            field=models.BooleanField(default=False, help_text='Auto create merchants as vendors in sage intacct'),
        ),
    ]
