# Generated by Django 3.2.14 on 2024-08-09 14:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0036_alter_configuration_is_journal_credit_billable'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='import_code_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PROJECT', 'PROJECT'), ('ACCOUNT', 'ACCOUNT'), ('DEPARTMENT', 'DEPARTMENT')], max_length=100), blank=True, default=list, help_text='Array Field to store code-naming preference', size=None),
        ),
    ]
