# Generated by Django 3.2.14 on 2024-08-14 09:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0037_configuration_import_code_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='import_code_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PROJECT', 'PROJECT'), ('ACCOUNT', 'ACCOUNT'), ('EXPENSE_TYPE', 'EXPENSE_TYPE'), ('_ACCOUNT', '_ACCOUNT'), ('_EXPENSE_TYPE', '_EXPENSE_TYPE'), ('DEPARTMENT', 'DEPARTMENT')], max_length=100), blank=True, default=list, help_text='Array Field to store code-naming preference', size=None),
        ),
    ]
