# Generated by Django 3.2.14 on 2024-11-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0038_alter_configuration_import_code_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='change_accounting_period',
            field=models.BooleanField(default=True, help_text='Change the accounting period'),
        ),
    ]
