# Generated by Django 4.2.20 on 2025-04-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0041_auto_20250108_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='is_simplify_report_closure_enabled',
        ),
    ]
