# Generated by Django 4.2.21 on 2025-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0044_configuration_je_single_credit_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceschedule',
            name='is_real_time_export_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
