# Generated by Django 4.2.20 on 2025-05-22 19:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0044_configuration_je_single_credit_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='top_level_memo_structure',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text='list of system fields for creating custom description for top level', size=None),
        ),
    ]
