# Generated by Django 4.2.20 on 2025-05-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0044_configuration_je_single_credit_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='sageintacctcredential',
            name='is_expired',
            field=models.BooleanField(default=False, help_text='Sage Intacct Password expiry flag'),
        ),
    ]
