# Generated by Django 4.2.21 on 2025-06-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0045_sageintacctcredential_is_expired'),
        ('workspaces', '0045_workspaceschedule_is_real_time_export_enabled'),
    ]

    operations = [
    ]
