# Generated by Django 4.2.22 on 2025-07-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0047_configuration_top_level_memo_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastexportdetail',
            name='unmapped_card_count',
            field=models.IntegerField(default=0, help_text='count of unmapped card'),
        ),
    ]
