# Generated by Django 4.2.24 on 2025-09-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0049_featureconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureconfig',
            name='import_via_rabbitmq',
            field=models.BooleanField(default=False, help_text='Enable import via rabbitmq'),
        ),
        migrations.AlterField(
            model_name='featureconfig',
            name='export_via_rabbitmq',
            field=models.BooleanField(default=False, help_text='Enable export via rabbitmq'),
        ),
    ]
