# Generated by Django 4.2.24 on 2025-09-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0050_featureconfig_import_via_rabbitmq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureconfig',
            name='export_via_rabbitmq',
            field=models.BooleanField(default=True, help_text='Enable export via rabbitmq'),
        ),
        migrations.AlterField(
            model_name='featureconfig',
            name='import_via_rabbitmq',
            field=models.BooleanField(default=True, help_text='Enable import via rabbitmq'),
        ),
    ]
