# Generated by Django 4.2.25 on 2025-10-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0051_alter_featureconfig_export_via_rabbitmq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureconfig',
            name='fyle_webhook_sync_enabled',
            field=models.BooleanField(default=False, help_text='Enable fyle attribute webhook sync'),
        ),
    ]
