# Generated by Django 4.2.26 on 2025-11-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0052_featureconfig_fyle_webhook_sync_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sageintacctcredential',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='Stores Sage Intacct refresh token', null=True),
        ),
    ]
