# Generated by Django 4.2.26 on 2025-11-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0054_alter_featureconfig_fyle_webhook_sync_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureconfig',
            name='migrated_to_rest_api',
            field=models.BooleanField(default=False, help_text='Migrated to using rest api'),
        ),
    ]
