# Generated by Django 4.2.26 on 2025-11-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0055_featureconfig_migrated_to_rest_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='sageintacctcredential',
            name='access_token',
            field=models.TextField(blank=True, help_text='Stores Sage Intacct access token', null=True),
        ),
        migrations.AddField(
            model_name='sageintacctcredential',
            name='access_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Stores Sage Intacct access token expiration time', null=True),
        ),
    ]
