# Generated by Django 4.2.26 on 2025-11-17 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0056_sageintacctcredential_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntacctSyncedTimestamp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_synced_at', models.DateTimeField(help_text='Datetime when accounts were synced last', null=True)),
                ('vendor_synced_at', models.DateTimeField(help_text='Datetime when vendors were synced last', null=True)),
                ('customer_synced_at', models.DateTimeField(help_text='Datetime when customers were synced last', null=True)),
                ('class_synced_at', models.DateTimeField(help_text='Datetime when classes were synced last', null=True)),
                ('employee_synced_at', models.DateTimeField(help_text='Datetime when employees were synced last', null=True)),
                ('item_synced_at', models.DateTimeField(help_text='Datetime when items were synced last', null=True)),
                ('location_synced_at', models.DateTimeField(help_text='Datetime when locations were synced last', null=True)),
                ('allocation_synced_at', models.DateTimeField(help_text='Datetime when allocations were synced last', null=True)),
                ('tax_detail_synced_at', models.DateTimeField(help_text='Datetime when tax details were synced last', null=True)),
                ('department_synced_at', models.DateTimeField(help_text='Datetime when departments were synced last', null=True)),
                ('project_synced_at', models.DateTimeField(help_text='Datetime when projects were synced last', null=True)),
                ('expense_type_synced_at', models.DateTimeField(help_text='Datetime when expense types were synced last', null=True)),
                ('location_entity_synced_at', models.DateTimeField(help_text='Datetime when location entities were synced last', null=True)),
                ('payment_account_synced_at', models.DateTimeField(help_text='Datetime when payment accounts were synced last', null=True)),
                ('expense_payment_type_synced_at', models.DateTimeField(help_text='Datetime when expense payment types were synced last', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
                ('workspace', models.ForeignKey(help_text='Reference to Workspace model', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'intacct_sync_timestamps',
            },
        ),
    ]
