# Generated by Django 4.2.27 on 2025-12-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0057_intacctsyncedtimestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sageintacctcredential',
            name='refresh_token',
        ),
        migrations.AlterField(
            model_name='sageintacctcredential',
            name='si_user_password',
            field=models.TextField(blank=True, help_text='Stores Sage Intacct user password', null=True),
        ),
    ]
