# Generated by Django 4.2.27 on 2025-12-11 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0057_intacctsyncedtimestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntacctCompanyToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.CharField(help_text='Company ID', max_length=255, unique=True)),
                ('refresh_token', models.TextField(help_text='Refresh Token')),
                ('access_token', models.TextField(blank=True, help_text='Access Token', null=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, help_text='Access Token Expiration Time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
            ],
            options={
                'db_table': 'intacct_company_tokens',
            },
        ),
        migrations.AddField(
            model_name='sageintacctcredential',
            name='company_token',
            field=models.ForeignKey(blank=True, help_text='Reference to IntacctCompanyToken model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sage_intacct_credentials', to='workspaces.intacctcompanytoken'),
        ),
    ]
