# Generated by Django 4.2.27 on 2026-01-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0058_remove_sageintacctcredential_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureconfig',
            name='import_billable_field_for_projects',
            field=models.BooleanField(default=False, help_text='Import billable field for projects'),
        ),
    ]
