# Generated by Django 4.2.27 on 2025-12-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0058_intacctcompanytoken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sageintacctcredential',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='sageintacctcredential',
            name='access_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='sageintacctcredential',
            name='refresh_token',
        ),
    ]
