# Generated by Django 4.2.27 on 2026-01-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0059_featureconfig_import_billable_field_for_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='regional_settings',
            field=models.JSONField(default=dict, help_text='Regional Settings'),
        ),
    ]
