data = {
    'workspace_general_settings_payload':{'id': 1, 'workspace': 1, 'employee_field_mapping': 'VENDOR', 'reimbursable_expenses_object': 'BILL', 'corporate_credit_card_expenses_object': 'BILL', 'import_projects': True, 'import_categories': False, 'sync_fyle_to_sage_intacct_payments': True, 'sync_sage_intacct_to_fyle_payments': False, 'auto_map_employees': 'EMAIL', 'import_tax_codes': True, 'memo_structure': ['employee_email', 'category', 'spent_on', 'report_number', 'purpose', 'expense_link'], 'auto_create_destination_entity': True, 'change_accounting_period': True, 'import_vendors_as_merchants': True, 'created_at': '2022-09-20T08:39:32.015647Z', 'updated_at': '2022-09-20T08:46:24.926422Z'},
    'workspace':{'id': 1, 'name': 'Fyle For Arkham Asylum', 'fyle_org_id': 'or79Cob97KSh', 'cluster_domain': 'https://staging.fyle.tech', 'last_synced_at': '2022-09-20T08:56:50.098426Z', 'source_synced_at': '2022-09-20T08:39:12.023205Z', 'destination_synced_at': '2022-09-20T08:40:27.770343Z', 'created_at': '2022-09-20T08:38:03.352044Z', 'updated_at': '2022-09-20T08:56:50.098865Z', 'user': [1]},
    'expenses':[
        {
            'id':91,
            'employee_email':'ashwin.t@fyle.in',
            'employee_name':'Joanna',
            'category':'Food',
            'sub_category':None,
            'project':'Aaron Abbott',
            'org_id':'or79Cob97KSh',
            'expense_id':'txxTi9ZfdepC',
            'expense_number':'E/2022/05/T/16',
            'claim_number':'C/2022/05/R/4',
            'amount':50.0,
            'currency':'USD',
            'foreign_amount':None,
            'foreign_currency':None,
            'tax_amount':None,
            'tax_group_id':None,
            'settlement_id':'setDiksMn83K7',
            'reimbursable':True,
            'billable':False,
            'exported':False,
            'state':'PAYMENT_PROCESSING',
            'vendor':'Ashwin',
            'cost_center':'Marketing',
            'purpose':None,
            'report_id':'rpViBmuYmAgw',
            'corporate_card_id':None,
            'file_ids':[
                
            ],
            'spent_at':'2022-05-13T17:00:00Z',
            'approved_at':'2022-05-13T09:30:13.484000Z',
            'expense_created_at':'2022-05-13T09:29:43.535468Z',
            'expense_updated_at':'2022-05-13T09:32:06.643941Z',
            'created_at':'2022-05-23T11:11:28.241406Z',
            'updated_at':'2022-05-23T11:11:28.241440Z',
            'fund_source':'PERSONAL',
            'source_account_type': 'PERSONAL_CASH_ACCOUNT',
            'verified_at':'2022-05-23T11:11:28.241440Z',
            'custom_properties':{
                'Team':'',
                'Class':'',
                'Klass':'',
                'Location':'',
                'Team Copy':'',
                'Tax Groups':'',
                'Departments':'',
                'Team 2 Postman':'',
                'User Dimension':'',
                'Location Entity':'',
                'Operating System':'',
                'System Operating':'',
                'User Dimension Copy':'',
                'Custom Expense Field':'None'
            },
            'paid_on_qbo':False,
            'payment_number':'P/2022/05/R/7'
        }
    ],
    'workspace_schedule': {'id': 1, 'enabled': True, 'start_datetime': '2022-09-26T13:08:16.281604Z', 'interval_hours': 1, 'error_count': None, 'additional_email_options': [], 'emails_selected': ['ashwin.t@fyle.in'], 'workspace': 1, 'schedule': 9}
}